fix(buffer): skip `UTF16` hoisted instance;
- cloudflare does not support non-utf8 atm
RangeError: TextDecoder only supports utf-8 encoding from  new TextDecoder("utf-16le")